### ISSUE TITLE
Target class [Webkul\Shop\Repositories\ThemeCustomizationRepository] does not exist.

### ISSUE THREAD

**Issue by CanhhnaC** [webbycrown/blog-for-bagisto#1]
i have error ThemeCustomizationRepository when i create bagisto with docker. Please help me

![image](https://github.com/webbycrown/blog-for-bagisto/assets/46088035/24734d2c-509b-4968-a298-a7d0a8b9a78b)

![image](https://github.com/webbycrown/blog-for-bagisto/assets/46088035/8e67dcc9-4896-4c44-93b8-436aca43dccf)

**Comment by yamahdico** [comment]
Hello dear, I also encountered this issue, please help us.

**Comment by akashcsoni** [comment]
This issue is solved.
