### ISSUE TITLE
Duplicate Routes

### ISSUE THREAD

**Issue by amirseyedian** [webbycrown/blog-for-bagisto#13]
I have found a duplicate route that causes
`Unable to prepare route [api/v1/blog/tag] for serialization. Another route has already been assigned name [shop.blog.category.list].`
on running `php artisan optimize`
and may be the cause of #11 by @KharisG1234T

>vendor/webbycrown/blog-for-bagisto/src/Routes/shop-routes.php

line 36,37

```
    Route::get('/api/v1/blog/category', 'Webbycrown\BlogBagisto\Http\Controllers\Shop\API\Blogs\BlogController@category_list')->name('shop.blog.category.list');
    Route::get('/api/v1/blog/tag', 'Webbycrown\BlogBagisto\Http\Controllers\Shop\API\Blogs\BlogController@tag_list')->name('shop.blog.category.list');
```
fix shop.blog.category.list to shop.blog.tag.category.list

**Comment by akashcsoni** [comment]
Hello @amirseyedian 

Thank you, the issue is resolved.
